recipes:
  heart:
    enabled: true
    result:
      material: NETHER_STAR
      name: "&cHeart"
      lore:
        - "&7Right click to gain +1 heart"
    shape:
      - "GGG"
      - "GHG"
      - "GGG"
    ingredients:
      G: GOLD_INGOT
      H: NETHER_STAR